package com.example.template.jpageneration;
// Generated Jan 31, 2018 5:00:28 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeightClaim generated by hbm2java
 */
@Entity
@Table(name="WEIGHT_CLAIM"
    ,catalog="SCORE_DEV_002"
)
public class WeightClaim  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pkWeightClaimId;
     private Integer fkShipmentOrderId;
     private Integer fkShipmentOrderShipmentAdviceId;
     private Integer fkStockId;
     private BigDecimal netWeightAtShipment;
     private BigDecimal netWeightAtWh;
     private BigDecimal franchisePct;
     private BigDecimal allowedFranchiseWeightLoss;
     private BigDecimal claimableWeightLoss;
     private Integer fkWeightUomId;
     private Integer fkStatusId;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String customAttribute1;
     private String customAttribute2;
     private String customAttribute3;
     private String customAttribute4;
     private String customAttribute5;
     private BigDecimal customAttribute6;
     private BigDecimal customAttribute7;
     private BigDecimal customAttribute8;

    public WeightClaim() {
    }

	
    public WeightClaim(int pkWeightClaimId) {
        this.pkWeightClaimId = pkWeightClaimId;
    }
    public WeightClaim(int pkWeightClaimId, Integer fkShipmentOrderId, Integer fkShipmentOrderShipmentAdviceId, Integer fkStockId, BigDecimal netWeightAtShipment, BigDecimal netWeightAtWh, BigDecimal franchisePct, BigDecimal allowedFranchiseWeightLoss, BigDecimal claimableWeightLoss, Integer fkWeightUomId, Integer fkStatusId, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String customAttribute1, String customAttribute2, String customAttribute3, String customAttribute4, String customAttribute5, BigDecimal customAttribute6, BigDecimal customAttribute7, BigDecimal customAttribute8) {
       this.pkWeightClaimId = pkWeightClaimId;
       this.fkShipmentOrderId = fkShipmentOrderId;
       this.fkShipmentOrderShipmentAdviceId = fkShipmentOrderShipmentAdviceId;
       this.fkStockId = fkStockId;
       this.netWeightAtShipment = netWeightAtShipment;
       this.netWeightAtWh = netWeightAtWh;
       this.franchisePct = franchisePct;
       this.allowedFranchiseWeightLoss = allowedFranchiseWeightLoss;
       this.claimableWeightLoss = claimableWeightLoss;
       this.fkWeightUomId = fkWeightUomId;
       this.fkStatusId = fkStatusId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.customAttribute1 = customAttribute1;
       this.customAttribute2 = customAttribute2;
       this.customAttribute3 = customAttribute3;
       this.customAttribute4 = customAttribute4;
       this.customAttribute5 = customAttribute5;
       this.customAttribute6 = customAttribute6;
       this.customAttribute7 = customAttribute7;
       this.customAttribute8 = customAttribute8;
    }
   
     @Id 
    
    @Column(name="PK_WEIGHT_CLAIM_ID", unique=true, nullable=false)
    public int getPkWeightClaimId() {
        return this.pkWeightClaimId;
    }
    
    public void setPkWeightClaimId(int pkWeightClaimId) {
        this.pkWeightClaimId = pkWeightClaimId;
    }
    
    @Column(name="FK_SHIPMENT_ORDER_ID")
    public Integer getFkShipmentOrderId() {
        return this.fkShipmentOrderId;
    }
    
    public void setFkShipmentOrderId(Integer fkShipmentOrderId) {
        this.fkShipmentOrderId = fkShipmentOrderId;
    }
    
    @Column(name="FK_SHIPMENT_ORDER_SHIPMENT_ADVICE_ID")
    public Integer getFkShipmentOrderShipmentAdviceId() {
        return this.fkShipmentOrderShipmentAdviceId;
    }
    
    public void setFkShipmentOrderShipmentAdviceId(Integer fkShipmentOrderShipmentAdviceId) {
        this.fkShipmentOrderShipmentAdviceId = fkShipmentOrderShipmentAdviceId;
    }
    
    @Column(name="FK_STOCK_ID")
    public Integer getFkStockId() {
        return this.fkStockId;
    }
    
    public void setFkStockId(Integer fkStockId) {
        this.fkStockId = fkStockId;
    }
    
    @Column(name="NET_WEIGHT_AT_SHIPMENT", precision=22, scale=6)
    public BigDecimal getNetWeightAtShipment() {
        return this.netWeightAtShipment;
    }
    
    public void setNetWeightAtShipment(BigDecimal netWeightAtShipment) {
        this.netWeightAtShipment = netWeightAtShipment;
    }
    
    @Column(name="NET_WEIGHT_AT_WH", precision=22, scale=6)
    public BigDecimal getNetWeightAtWh() {
        return this.netWeightAtWh;
    }
    
    public void setNetWeightAtWh(BigDecimal netWeightAtWh) {
        this.netWeightAtWh = netWeightAtWh;
    }
    
    @Column(name="FRANCHISE_PCT", precision=22, scale=6)
    public BigDecimal getFranchisePct() {
        return this.franchisePct;
    }
    
    public void setFranchisePct(BigDecimal franchisePct) {
        this.franchisePct = franchisePct;
    }
    
    @Column(name="ALLOWED_FRANCHISE_WEIGHT_LOSS", precision=22, scale=6)
    public BigDecimal getAllowedFranchiseWeightLoss() {
        return this.allowedFranchiseWeightLoss;
    }
    
    public void setAllowedFranchiseWeightLoss(BigDecimal allowedFranchiseWeightLoss) {
        this.allowedFranchiseWeightLoss = allowedFranchiseWeightLoss;
    }
    
    @Column(name="CLAIMABLE_WEIGHT_LOSS", precision=22, scale=6)
    public BigDecimal getClaimableWeightLoss() {
        return this.claimableWeightLoss;
    }
    
    public void setClaimableWeightLoss(BigDecimal claimableWeightLoss) {
        this.claimableWeightLoss = claimableWeightLoss;
    }
    
    @Column(name="FK_WEIGHT_UOM_ID")
    public Integer getFkWeightUomId() {
        return this.fkWeightUomId;
    }
    
    public void setFkWeightUomId(Integer fkWeightUomId) {
        this.fkWeightUomId = fkWeightUomId;
    }
    
    @Column(name="FK_STATUS_ID")
    public Integer getFkStatusId() {
        return this.fkStatusId;
    }
    
    public void setFkStatusId(Integer fkStatusId) {
        this.fkStatusId = fkStatusId;
    }
    
    @Column(name="CREATED_BY", length=100)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=23)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="MODIFIED_BY", length=100)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE", length=23)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_1", length=500)
    public String getCustomAttribute1() {
        return this.customAttribute1;
    }
    
    public void setCustomAttribute1(String customAttribute1) {
        this.customAttribute1 = customAttribute1;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_2", length=500)
    public String getCustomAttribute2() {
        return this.customAttribute2;
    }
    
    public void setCustomAttribute2(String customAttribute2) {
        this.customAttribute2 = customAttribute2;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_3", length=500)
    public String getCustomAttribute3() {
        return this.customAttribute3;
    }
    
    public void setCustomAttribute3(String customAttribute3) {
        this.customAttribute3 = customAttribute3;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_4", length=500)
    public String getCustomAttribute4() {
        return this.customAttribute4;
    }
    
    public void setCustomAttribute4(String customAttribute4) {
        this.customAttribute4 = customAttribute4;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_5", length=500)
    public String getCustomAttribute5() {
        return this.customAttribute5;
    }
    
    public void setCustomAttribute5(String customAttribute5) {
        this.customAttribute5 = customAttribute5;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_6", precision=22, scale=6)
    public BigDecimal getCustomAttribute6() {
        return this.customAttribute6;
    }
    
    public void setCustomAttribute6(BigDecimal customAttribute6) {
        this.customAttribute6 = customAttribute6;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_7", precision=22, scale=6)
    public BigDecimal getCustomAttribute7() {
        return this.customAttribute7;
    }
    
    public void setCustomAttribute7(BigDecimal customAttribute7) {
        this.customAttribute7 = customAttribute7;
    }
    
    @Column(name="CUSTOM_ATTRIBUTE_8", precision=22, scale=6)
    public BigDecimal getCustomAttribute8() {
        return this.customAttribute8;
    }
    
    public void setCustomAttribute8(BigDecimal customAttribute8) {
        this.customAttribute8 = customAttribute8;
    }




}


